export default [{
    id: 1,
    name: 'LIBRARIAN_CREATE',
}, {
    id: 2,
    name: 'LIBRARIAN_DELETE',
}, {
    id: 3,
    name: 'LIBRARIAN_EDIT',
}, {
    id: 4,
    name: 'LIBRARIAN_READ',
}, {
    id: 5,
    name: 'BOOK_CREATE',
}, {
    id: 6,
    name: 'BOOK_EDIT',
}, {
    id: 7,
    name: 'BOOK_READ',
}, {
    id: 8,
    name: 'ITEM_CREATE',
}, {
    id: 9,
    name: 'ITEM_DELETE',
}, {
    id: 10,
    name: 'ITEM_READ',
}, {
    id: 11,
    name: 'SETTINGS_CREATE',
}, {
    id: 12,
    name: 'SETTINGS_EDIT',
}, {
    id: 13,
    name: 'SETTINGS_READ',
}, {
    id: 14,
    name: 'SETTINGS_DELETE',
}, ]